name: ci 
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 1,3,5"  # Runs every Monday, Wednesday, and Friday at 4 PM UTC

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material google-generativeai mkdocs-material-extensions
      - run: export PYTHONPATH=. ;mkdocs gh-deploy --force