name: Run and Update

on:
  schedule:
    - cron: "0 16 * * 1,3,5"  # Runs every Monday, Wednesday, and Friday at 4 PM UTC
  workflow_dispatch:

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements 
        run: pip install google-generativeai

      - name: Run testfile.py
        run: python testfile.py

      - name: Run update.py
        env:
  GEMINI_API_KEY: ${{ secrets.API_KEY }}
        run: python update.py

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "infibrocco"
          git config --global user.email "infibrocco@yopmail.com"
          git add --all
          git commit -m "Automated update" || echo "No changes to commit"
          git push https://infibrocco:${GH_PAT}@github.com/infibrocco/mk-blog-test.git HEAD:main

